### ISSUE TITLE
Rolling autocorrelation

### ISSUE THREAD

**Issue by flare9x** [dysonance/Indicators.jl#10]
This is the shell of an idea. Not wrapped in a clean function. It has demean. Function would include demean=true,false 

# Rolling Autocorrelation
# Sliding window (k width)
mean_out = zeros(size(d_es_close,1))
var_out = zeros(size(d_es_close,1))
cov_out = zeros(size(d_es_close,1))
autocor_out = zeros(size(d_es_close,1))
devmean_out = zeros(size(d_es_close,1))
n=1000
k = 1 # set lag
n_lag = 100 # return series lag

# Calculate bar return series
rets = zeros(size(d_es_close,1))
for i in n_lag+1:length(d_es_close)
    rets[i] = ((d_es_close[i] / d_es_close[i-n_lag])-1) # rets[i] = ((d_es_close[i] / d_es_close[i-n_lag+1])-1)
end

# lag the series by k
lagged_series = [fill(0,k); rets[1:end-k]]

# Calculate the mean of the rolling  sample
for i = n:size(rets,1)
    mean_out[i] = mean(rets[i-n+1:i])
end

# Calculate deviations from the mean
for i = n:size(rets,1)
devmean_out[i] = rets[i] - mean_out[i]
end

# Calculate rolling variance
for i = n:size(rets,1)
    var_out[i] = var(rets[i-n+1:i])
end

# Calculate rolling covariance
for i = n:size(rets,1)
    if i+k >= size(rets,1)
        break
    end
    cov_out[i] = cov(rets[i-n+1:i],lagged_series[i-n+1:i])
end

# Rolling Autocorrelation
for i =n:size(rets,1)
    autocor_out[i] = cov_out[i] / var_out[i]
end

It's simply the covariance of the series and some lag of itself / variance. 

Il see if I can wrap it in a clean function when I get a chance!

**Comment by JTAmos** [comment]
@flare9x Sorry I'm just now getting around to replying to this (I was off the grid for two weeks on my honeymoon 😃).

I think this is a pretty cool idea. Just so you're aware, there are quite a few functions in the `src/run.jl` file for computing various statistics like covariance and correlation on a rolling or running/cumulative basis (e.g. `runcov(x,y)` and `runcor(x,y)` respectively).

For rolling autocorrelation, my initial strategy would be take a `Vector` object as input (plus the lookback period, autocorrelation lags, and other args) and output a `Matrix` where each row corresponds to a timestep and each column corresponds to a lag interval. So if you wanted rolling autocorrelation of an Nx1 series of returns with a lookback of 10 and a max lag of 10, you'd get a `Matrix` object of dimension Nx11 (where the first column would be all ones, the second would be the first lag, and so on). What do you think of this approach?

I will try and get started on a prototype of this strategy.

**Comment by flare9x** [comment]
Yup that would be perfect. Over the n lag period. You may plot a heatmap of the output coefficients. So at any time stamp at varying lags you may see what the correlation coefficient was. Sounds good! And Congratulations!! Where did you get married? Wife and I eloped to Jamaica about 1.5 hours ago now :)

**Comment by JTAmos** [comment]
@flare9x Just pushed some work on this to branch `issue10`. Go ahead and check it out and see what you think — feel free to suggest/make any edits/changes. I'd also recommend making sure you have checked out the master branch of Temporal.jl as well, as there is a dependency there that I was making changes to as I was coding.

And thank you! We got married a year ago but work was too hectic to be able to honeymoon then, so we decided to put it off for a year. But we definitely made up for the delay with a gorgeous two weeks seeing all different parts of England. Congratulations to you and your wife as well 😃 🎊

**Comment by JTAmos** [comment]
@flare9x Heads up that this functionality has been added and merged into master. I will plan to open pull requests to the Julia `METADATA.jl` repository with new releases soon.

I'm going to close this issue for now, feel free to re-open or create a new one if you find something that seems off or if there's some other functionality you'd like.

Cheers and thanks again for the good ideas. Keep em coming.

**Comment by Sinansi** [comment]
> @flare9x Sorry I'm just now getting around to replying to this (I was off the grid for two weeks on my honeymoon 😃).
> 
> I think this is a pretty cool idea. Just so you're aware, there are quite a few functions in the `src/run.jl` file for computing various statistics like covariance and correlation on a rolling or running/cumulative basis (e.g. `runcov(x,y)` and `runcor(x,y)` respectively).
> 
> For rolling autocorrelation, my initial strategy would be take a `Vector` object as input (plus the lookback period, autocorrelation lags, and other args) and output a `Matrix` where each row corresponds to a timestep and each column corresponds to a lag interval. So if you wanted rolling autocorrelation of an Nx1 series of returns with a lookback of 10 and a max lag of 10, you'd get a `Matrix` object of dimension Nx11 (where the first column would be all ones, the second would be the first lag, and so on). What do you think of this approach?
> 
> I will try and get started on a prototype of this strategy.

I didnt know you have running statistics in this library until I saw this comment. 
I kindly ask you to include all the indicators in the documentation.
Thank you!
