### ISSUE TITLE
Rolling hurst rescaled range analysis method

### ISSUE THREAD

**Issue by flare9x** [dysonance/Indicators.jl#11]
https://gist.github.com/flare9x/76fe49368f14e652f6de3a130344ea4e#file-rolling_rs_hurst-jl

This is over lapping blocks of varying lags on a return series. Each data point in the series then has a H value. Needs to be wrapped in a clean function.

**Comment by JTAmos** [comment]
I've been meaning to get cracking on this domain area of indicator functions for some time. Glad to hear there's some demand for this functionality now. Hopefully I'll get some time to start on this very soon 😎

**Comment by JTAmos** [comment]
@flare9x  I've gotten a very small start on this work. The code I've added is pushed to branch `issue11` if you'd like to take a look and review. This methodology is still a bit fresh to me so I've been focusing mostly on understanding the logic and algorithm going off of papers and references online, hence it's not unlikely that I've missed something calculation-wise.

Right now I've got preliminary implementations for static rescaled range and Hurst exponent estimation functions, code is in `src/chaos.jl` if you wanna take a gander. I haven't yet had time to look closely at your implementation but I'd still like to do so as it seems like you put a lot of thought into it and there's probably some stuff we could borrow from one another.

Hope to continue working on this next week, time permitting work-wise. Anyway, let me know if you have any thoughts, cheers, and have a good weekend.

**Comment by JTAmos** [comment]
@flare9x I think I've made good progress and just about have this done. Sorry for the delay, been a busy time at work lately, but I'm working on getting everything tested and all set to publish a new version to Juila's main public package manager. In the meantime, you can feel free to pull from the master branch if you wanna take a look in the meantime. Going to close this for now, feel free to re-open if more to be done or if something looks off. Cheers and thanks again for the good idea.
