### ISSUE TITLE
BigFloat support

### ISSUE THREAD

**Issue by xgdgsc** [dysonance/Indicators.jl#18]
Provide generic functions to be able to used by other numeric types like BigFloat.

**Comment by JTAmos** [comment]
Hey @xgdgsc, thanks for suggesting this! I've made the changes that should allow this and merged them through [this pull request](https://github.com/dysonance/Indicators.jl/pull/19) and drafted a new release versioned at [v0.7.0](https://github.com/dysonance/Indicators.jl/releases/tag/v0.7.0). So once that's merged into Julia's METADATA repository, then this should be good to go.

Thanks again for the good suggestion.
