### ISSUE TITLE
Not working with Julia 1.2.0

### ISSUE THREAD

**Issue by wangtieqiao** [dysonance/Indicators.jl#21]
Try to run the examples not working:

-  first complain Dates is Undefined after adjusted `using Base.Dates` to `using Dates` passed
- then complain srand() Undefined, removed it passed
- then got following error otuput

MethodError: no method matching +(::Float64, ::Array{Float64,1})
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:529
  +(::Float64, !Matched::Float64) at float.jl:395
  +(!Matched::PyCall.PyObject, ::Any) at /home/steve/.julia/packages/PyCall/ttONZ/src/pyoperators.jl:13
  ...

Stacktrace:
 [1] top-level scope at In[5]:8

**Comment by JTAmos** [comment]
@stevewangldcap Thanks for raising this, I will investigate and try to get something worked out.

**Comment by JTAmos** [comment]
@stevewangldcap Try pulling the latest master and see if it works. If not go ahead and post some more details about what's failing and I can take another crack at it.
