### ISSUE TITLE
Tag a new release to improve compatibility

### ISSUE THREAD

**Issue by Moelf** [dysonance/Indicators.jl#29]
Hi,
we should tag a new release and remove Manifest.toml; at the moment, for example, `Plots.jl` is pinned at 0.29.0 which is really old.

**Comment by JTAmos** [comment]
Release published: https://github.com/dysonance/Indicators.jl/releases/tag/v0.8.0

**Comment by Moelf** [comment]
thx, btw, now most packages don't use Manifest.toml it seems, it's helpful to relax the versions of other packages so that they don't have to be pinned exactly.
