### ISSUE TITLE
Renko

### ISSUE THREAD

**Issue by balupton** [dysonance/Indicators.jl#4]
Any plans for Renko support?

- https://www.tradingview.com/wiki/Renko_Charts
- http://stockcharts.com/school/doku.php?id=chart_school:chart_analysis:renko
- http://www.investopedia.com/terms/r/renkochart.asp

**Comment by JTAmos** [comment]
@balupton Added `renko` functions with my latest commits. Take a look and let me know what you think and if this is something along the lines of what you had in mind.

I've made a pull request to `METADATA.jl` to have the package updates published publicly, but in the mean time if you're eager to start using feel free to pull the changes from the `Indicators.jl` master branch manually.

Gonna close this issue for now. Let me know if there's more that can be done and I can re-open or create a new issue.

Cheers and thanks for the feature suggestion.
