### ISSUE TITLE
Adding support for AlphaVantage

### ISSUE THREAD

**Issue by Balinus** [dysonance/Indicators.jl#7]
Hello!

Just found out about your packages. Looks nice! I was wondering if you were planning support for AlphaVantage API? There's a package developed in Julia right now https://github.com/ellisvalentiner/AlphaVantage.jl

Cheers!

**Comment by JTAmos** [comment]
@Balinus Thanks for the kind words and the excellent suggestion. I definitely think this would be a great addition, but would probably be more appropriately suited as another I/O feature for [Temporal.jl](https://github.com/dysonance/Temporal.jl) (a separate package I maintain offering another time series object type, `TS`). It already has API interfaces for Quandl, Google Finance, and Yahoo Finance, so adding support for AlphaVantage would make for a great enhancement.

That being said, I was not aware until just not checking out their [API docs](https://www.alphavantage.co/documentation/#technical-indicators) that you could also do API calls for technical indicators, which I assume is what you're more specifically interested in? There definitely is a nice list of indicators that they offer, and this list would be a great reference point to consider other new indicators to add to this package.

Are there any indicators in particular that you are after? If so, I can try to prioritize those and get cracking on some implementations here.

**Comment by Balinus** [comment]
Well, I did some work, using AlphaVantage.jl package and reformated the output into a TimeArray so that indeed, I could get some indicators from MarketTechnicals package. I've read your post about the advantages/disadvantages of TimeArray vs your Temporal.jl package. On my end, I do not mind which type is used, as long as I can compute some indicators and plot the results!

In this sense, I do not have any preference for indicators, I know my ways with Julia enough so I can go from TS type to TimeArray type and vice-versa with some generic wrapper code and calculate the indicators I need. Of course, the ideal package would do everything, from getting the data, indicator calculation and then plotting the results, with exportation functions to csv or sql databases, all through an unified packages eco-system!

I will get a closer look at Temporal. Looks interesting and just found about it last week. I'll see if I can contribute here and there.  Cheers!

**Comment by femtotrader** [comment]
Not sure if data readers should be part of Temporal or should be in a separate repository (with several kind of output: [Temporal](https://github.com/dysonance/Temporal.jl), [TimeSeries](https://github.com/JuliaStats/TimeSeries.jl), [DataFrame](https://github.com/JuliaData/DataFrames.jl), [IndexedTable](https://github.com/JuliaComputing/IndexedTables.jl), ... thanks to [IterableTables](https://github.com/davidanthoff/IterableTables.jl))

I did something (which is now broken) on https://github.com/femtotrader/DataReaders.jl

See https://github.com/dysonance/Temporal.jl/issues/21

**Comment by JTAmos** [comment]
Closing as out-of-scope for purpose of package meant to focus on calculation engines within Julia as opposed to remote API calls.
