### ISSUE TITLE
Running Regression Support x,y input

### ISSUE THREAD

**Issue by flare9x** [dysonance/Indicators.jl#8]
Right now it regresses x as some index and y the dependent y::Array{Float64} input.

If I wanted to a run a regression between two variables, well I guess could change the xi part of the function to accept an Array input for x. 

Lets say VIX and ES mini are sorted per date and want to find a rolling regression between ES / VIX (x,y) 

Or in co-integration pairs trading, One may wish to run a rolling linear regression between Stock A / B. One as x,y independent/dependent variables. 

An ADF test would be fantastic also :) 

Great work. I just found Julia a few days ago and liking this package as I was familiar with TTR.

**Comment by JTAmos** [comment]
Hey @flare9x thanks for the good suggestion, take a look at the pull request I opened to add this feature. Let me know if it's what you're after or if I didn't understand correctly.

Also, just wanted to say thanks for mentioning this package on one of your recent blog posts — very much appreciate the shout-out, and the blog post itself was really interesting in my opinion, so thumbs up all around 👍

**Comment by JTAmos** [comment]
@flare9x This has been merged into master, let me know if more to be done. I will try to get it put into the Julia METADATA repo today so its widely available.

**Comment by flare9x** [comment]
Hey! Sorry for such a late reply - i have been SUPER busy. I have not checked it out yet, i'm sure it is as intended. I am working on a rolling Hurst and Fisher transform. One method for calculating the hurst was to plot a regression of the lagged differences and the time lag number and divide the slope by 2 (Ernie Chan method). So that method I will be calling the rolling regression for sure. Another calculation was to estimate hurst by stdev, mean, min and max and divide the min,max difference by the standard deviation and take the log of that / length of the series (or rolling window) Anyway! Both are interesting - Once I finish - Perhaps its something you might want to review and incorporate to the package.
